# Generated by Django 3.0.1 on 2020-01-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('date_of_publication', models.DateTimeField(verbose_name='Date Published')),
                ('banner_image', models.ImageField(upload_to='', verbose_name='Banner Image')),
                ('author', models.CharField(max_length=1024, verbose_name='Author')),
            ],
        ),
    ]
